=encoding utf-8

=head1 NAME

RPC::Pipelined - Promise pipelining

=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 SEE ALSO

L<RPC-Pipelined github repo|https://github.com/hoytech/RPC-Pipelined>

=head1 AUTHOR

Doug Hoyte, C<< <doug@hcsw.org> >>

=head1 COPYRIGHT & LICENSE

Copyright 2014 Doug Hoyte.

This module is licensed under the same terms as perl itself.
